project_id = "kotor-walls"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/**"]

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.validate-ticket]
verify_jwt = false

[functions.kw-view-tickets]
verify_jwt = false
